"""empty message

Revision ID: 1cdde47ac8ba
Revises: e7f0ca79e797
Create Date: 2024-03-20 14:11:24.666234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdde47ac8ba'
down_revision = 'e7f0ca79e797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('is_new')
        batch_op.drop_column('description')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
