"""empty message

Revision ID: 7e673d9fa5cf
Revises: 218ab44f2691
Create Date: 2024-03-20 14:08:03.888448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e673d9fa5cf'
down_revision = '218ab44f2691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('is_new')
        batch_op.drop_column('description')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('deadline')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
