"""empty message

Revision ID: e73438cb54c9
Revises: 83fd04ae2e21
Create Date: 2024-03-20 14:05:26.801385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73438cb54c9'
down_revision = '83fd04ae2e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('is_new')
        batch_op.drop_column('description')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('deadline')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
